fix(player-interactions): prevent player from moving while interacting
FrancoisTouchard/IndigoProject pull request #22
Opened 2024-04-22 09:09 UTC by FrancoisTouchard

adding gameState.isPaused to hook to toggle pause state only once when interaction beginnins

2024-07-01 14:53 UTC, dezeeuwLouis commented
Attention tu a 24 commit pour 25 fichiers modifié, les message des commit ne sont pas toujours explicite, il faudrait surement revoir la manière dont ils sont groupés

2024-07-01 15:00 UTC, dezeeuwLouis requested changes

2024-07-01 15:00 UTC, dezeeuwLouis commented on src/components/GenericMenu/index.tsx
> +import { ListSelector } from 'src/screens/OpeningScreen/components/GameDisplay/GameScreen/PCMenu/ListSelector';
Même remarque que précédemment, ton sélecteur est uniquement utilisé dans ton menu générique, c'est donc dans ce composant qu'il dois être

2024-07-01 15:00 UTC, dezeeuwLouis commented on src/components/GenericMenu/useGenericMenu.ts
> +  const [selectorPosition, setSelectorPosition] = useState(0);
extraire '0' dans une `const INITIAL_SELECTOR_POSITION = 0`

2024-07-01 15:00 UTC, dezeeuwLouis commented on src/components/GenericMenu/useGenericMenu.ts
> +  const menuItemsLength = menuItems.length;
La variable n'est pas utile, très peu de changement entre la variable et son contenu

2024-07-01 15:00 UTC, dezeeuwLouis commented on src/screens/OpeningScreen/components/GameControls/DirectionalCross/useDirectionalCross.ts
> +  const playerOrientation = useRef<false | ArrowType>('up');
extraire 'up' dans une `const INITIAL_PLAYER_ORIENTATION = 'up'` tu peux migrer le commentaire avec la definition de la variable si tu en a encore besoin

2024-07-01 15:00 UTC, dezeeuwLouis commented on src/screens/OpeningScreen/components/GameDisplay/GameScreen/PCMenu/ListSelector/index.tsx
> +        { left: -leftOffset + LIST_SELECTOR_DIMENSIONS / 2 },
a extraire dans une variable, il faut prendre directement l'habitude de ne pas laisser des définition dans le render directement, c'est une mauvaise pratique sur laquelle on reviendra plus profondément pendant l'étape d'analyse des performances

2024-07-01 15:00 UTC, dezeeuwLouis commented on src/screens/OpeningScreen/components/GameDisplay/GameScreen/PCMenu/usePCMenu.ts
> +  const onExitPress = () => {};
il manque le comportement quand on appuie sur exit

2024-07-01 15:00 UTC, dezeeuwLouis commented on src/screens/OpeningScreen/components/GameDisplay/GameScreen/PlayerCurrentInteraction/PcInteraction/Pokedex/PokedexBorder/index.tsx
> +    width: WINDOW_WIDTH,
On ne peut pas utiliser 100% au lieu d'une valeur calculé par Dimensions ? sinon ont peut laisser

2024-07-01 15:00 UTC, dezeeuwLouis commented on src/screens/OpeningScreen/components/GameDisplay/GameScreen/PlayerCurrentInteraction/PcInteraction/Pokedex/PokedexBorder/index.tsx
> +    backgroundColor: '#1e81b0',
couleur a extraire dans le  fichier de config des couleurs

2024-07-01 15:00 UTC, dezeeuwLouis commented on src/screens/OpeningScreen/components/GameDisplay/GameScreen/PlayerCurrentInteraction/PcInteraction/Pokedex/PokedexBorder/index.tsx
> +    fontSize: 10,
extraire la font size et familly dans le fichier de config du style

2024-07-01 15:00 UTC, dezeeuwLouis commented on src/screens/OpeningScreen/components/GameDisplay/GameScreen/PlayerCurrentInteraction/PcInteraction/Pokedex/PokedexSingleRow/index.tsx
> +  textAlign: 'left' as const,
attention c'est incorrect 'as const' na pas besoin d'être utilisé, ici tu cast une string 'left' avec le type d'une const, ça n'a pas de sens

2024-07-01 15:00 UTC, dezeeuwLouis commented on src/screens/OpeningScreen/components/GameDisplay/GameScreen/PlayerCurrentInteraction/PcInteraction/Pokedex/PokedexSingleRow/index.tsx
> +  fontSize: 10,
extraire la font size et familly dans le fichier de config du style

2024-07-01 15:00 UTC, dezeeuwLouis commented on src/screens/OpeningScreen/components/GameDisplay/GameScreen/PlayerCurrentInteraction/PcInteraction/Pokedex/PokedexSingleRow/index.tsx
> +      <Text style={styles.pokemonNumber}>No {number}</Text>
```suggestion
      <Text style={[styles.singleRowContainer, styles.pokemonNumber]}>No {number}</Text>
```
utiliser la syntaxe mise a notre disposition par react plutot que de spread une variable dans ton style, fonctionnellement c'est identique mais c'est plus lisible de passer directement par la balise Text et son attribut style

2024-07-01 15:00 UTC, dezeeuwLouis commented on src/screens/OpeningScreen/components/GameDisplay/GameScreen/PlayerCurrentInteraction/PcInteraction/Pokedex/PokedexSingleRow/index.tsx
> +    width: WINDOW_WIDTH,
ont ne peut pas utiliser 100% ou flex ? sinon laisser tel quel

2024-07-01 15:00 UTC, dezeeuwLouis commented on src/screens/OpeningScreen/components/GameDisplay/GameScreen/PlayerCurrentInteraction/PcInteraction/Pokedex/PokedexSingleRow/index.tsx
> +    flex: 4,
ça me parait incorrect tu prend 4 fois l'espace disponible ici

2024-07-01 15:00 UTC, dezeeuwLouis commented on src/screens/OpeningScreen/components/GameDisplay/GameScreen/PlayerCurrentInteraction/PcInteraction/Pokedex/index.tsx
> +export const pokemonData: PokemonDataProps[] = [
deja defini dans src/screens/OpeningScreen/components/GameDisplay/GameScreen/PCMenu/usePCMenu.ts extraire dans un fichier de config en attendant que les donné revienne d'une api

2024-07-01 15:00 UTC, dezeeuwLouis commented on src/screens/OpeningScreen/components/GameDisplay/GameScreen/PlayerCurrentInteraction/PcInteraction/Pokedex/index.tsx
> +      <PokedexBorder text={'- POKéMON   LIST - '} />
a extraire dans une variable

2024-07-01 15:00 UTC, dezeeuwLouis commented on src/screens/OpeningScreen/components/GameDisplay/GameScreen/PlayerCurrentInteraction/PcInteraction/Pokedex/index.tsx
> +  }, []);
attention la logique est incorrecte ici, on va refaire un passe en vocal pour la partie pokedex

2024-07-01 15:00 UTC, dezeeuwLouis commented on src/screens/OpeningScreen/components/GameDisplay/GameScreen/PlayerCurrentInteraction/PcInteraction/Pokedex/index.tsx
> +        ))}
a remplacer par le composant générique de liste

2024-07-01 15:00 UTC, dezeeuwLouis commented on src/screens/OpeningScreen/components/GameDisplay/GameScreen/PlayerCurrentInteraction/PcInteraction/Pokedex/index.tsx
> +      <PokedexBorder text={'tips de NAVIGATION'} />
extraire le texte dans une variable

2024-07-01 15:00 UTC, dezeeuwLouis commented on src/screens/OpeningScreen/components/GameDisplay/GameScreen/PlayerCurrentInteraction/PcInteraction/Pokedex/index.tsx
> +    backgroundColor: '#F9F6EE',
extraire la couleur dans le fichier de config des couleurs

2024-07-01 15:00 UTC, dezeeuwLouis commented on src/screens/OpeningScreen/components/GameDisplay/GameScreen/PlayerCurrentInteraction/PcInteraction/Pokedex/usePokedex.tsx
> +  isPressed: ArrowType | false,
changer le type utilisé par isPressedType

2024-07-01 15:00 UTC, dezeeuwLouis commented on src/screens/OpeningScreen/components/GameDisplay/GameScreen/PlayerCurrentInteraction/PcInteraction/Pokedex/usePokedex.tsx
On repassera sur les logique associé au pokedex, ya du legacy code a supprimer et a remplacer par les nouvelle utilisation de la liste générique

2024-07-08 10:34 UTC, FrancoisTouchard commented on src/components/GenericMenu/index.tsx
> +    fontSize: 10,
création du fichier assets/appStyle.js incluant la fontFamily, fontSize + le contenu de assets/AnimationOpening/stylesColorsCode.js. 
-> suppression de assets/AnimationOpening/stylesColorsCode.js
-> correction des imports dans les fichiers ou les couleurs sont utilisées

2024-07-08 10:42 UTC, FrancoisTouchard commented on src/components/GenericMenu/index.tsx
> +} from 'src/screens/OpeningScreen/components/GameDisplay/GameScreen/PCMenu';
LIST_ITEM_HEIGHT et MENU_ITEMS_LEFT_OFFSET sont maintenant définies dans GenericMenu/index et importées dans PCMenu/index

2024-07-08 10:43 UTC, FrancoisTouchard commented on src/components/GenericMenu/index.tsx
> +import { ListSelector } from 'src/screens/OpeningScreen/components/GameDisplay/GameScreen/PCMenu/ListSelector';
ListSelector est importé dans GenericMenu et n'intervient pas dans PCMenu

2024-07-08 10:46 UTC, FrancoisTouchard commented on src/components/GenericMenu/useGenericMenu.ts
> +  const [selectorPosition, setSelectorPosition] = useState(0);
ok fait

2024-07-08 10:47 UTC, FrancoisTouchard commented on src/components/GenericMenu/useGenericMenu.ts
> +  const menuItemsLength = menuItems.length;
ok supprimée

2024-07-08 10:49 UTC, FrancoisTouchard commented on src/screens/OpeningScreen/components/GameControls/DirectionalCross/useDirectionalCross.ts
> +  const playerOrientation = useRef<false | ArrowType>('up');
ok fait, com supprimé

2024-07-08 10:55 UTC, FrancoisTouchard commented on src/screens/OpeningScreen/components/GameDisplay/GameScreen/PCMenu/ListSelector/index.tsx
> +        { left: -leftOffset + LIST_SELECTOR_DIMENSIONS / 2 },
création d'une variable ` const listSelectorLeftOffset = -leftOffset + LIST_SELECTOR_DIMENSIONS / 2; `

2024-07-08 12:52 UTC, FrancoisTouchard commented on src/screens/OpeningScreen/components/GameDisplay/GameScreen/PlayerCurrentInteraction/PcInteraction/Pokedex/PokedexBorder/index.tsx
> +    backgroundColor: '#1e81b0',
ok fait

2024-07-08 13:10 UTC, FrancoisTouchard commented on src/screens/OpeningScreen/components/GameDisplay/GameScreen/PlayerCurrentInteraction/PcInteraction/Pokedex/PokedexBorder/index.tsx
> +    fontSize: 10,
ok

2024-07-08 13:10 UTC, FrancoisTouchard commented on src/screens/OpeningScreen/components/GameDisplay/GameScreen/PlayerCurrentInteraction/PcInteraction/Pokedex/PokedexBorder/index.tsx
> +    width: WINDOW_WIDTH,
j'ai mis un commentaire pour penser à vérifier quand je ferai le pokédex juste après

2024-07-08 13:17 UTC, FrancoisTouchard commented on src/screens/OpeningScreen/components/GameDisplay/GameScreen/PlayerCurrentInteraction/PcInteraction/Pokedex/PokedexSingleRow/index.tsx
> +  textAlign: 'left' as const,
ok

2024-07-08 13:17 UTC, FrancoisTouchard commented on src/screens/OpeningScreen/components/GameDisplay/GameScreen/PlayerCurrentInteraction/PcInteraction/Pokedex/PokedexSingleRow/index.tsx
> +  fontSize: 10,
ok

2024-07-08 13:22 UTC, FrancoisTouchard commented on src/screens/OpeningScreen/components/GameDisplay/GameScreen/PlayerCurrentInteraction/PcInteraction/Pokedex/PokedexSingleRow/index.tsx
> +      <Text style={styles.pokemonNumber}>No {number}</Text>
ok fait

2024-07-08 13:23 UTC, FrancoisTouchard commented on src/screens/OpeningScreen/components/GameDisplay/GameScreen/PlayerCurrentInteraction/PcInteraction/Pokedex/PokedexSingleRow/index.tsx
> +    width: WINDOW_WIDTH,
ok

2024-07-08 14:11 UTC, FrancoisTouchard commented on src/screens/OpeningScreen/components/GameDisplay/GameScreen/PCMenu/usePCMenu.ts
> +  const onExitPress = () => {};
ok fait

2024-07-15 11:56 UTC, dezeeuwLouis approved these changes

2024-07-16 07:30 UTC, merged